const vars: any = {
  "primary-blue": "#ddebff",
  orange: "#fbb445",
  green: "#0dca9d",
  'light-green': '#E7FAF5',
  'light-yellow': '#FFF9E5',
  'light-red': '#FFF1F1',
  'heavy-red': '#FF7171',
  'heavy-yellow': '#FBB445',
  'heavy-green': '#0DCA9D',
  red: "#ff7171",
  black: "#808080",
  "extra-light-grey": "#f8fbff",
  "input-light-grey": "#F9F9F9",
  "light-grey": "#f5f4f4",
  "light-pink": "#fff0f9",
  "light-blue": "#f5f9ff",
  "medium-grey-lighter": "#b3b3b3",
  "medium-grey": "#b4b7bc",
  "medium-grey2": "#696f7a",
  grey: "#DDDDDD",
  "accent-blue": "#086afb",
  "accent-pink": "#e7038e",
  "accent-orange": "#fbb445",
  "accent-green": "#0dca9d",
  "soft-pink": "#ffc9e9",
  "lg-breakpoint": "1440px",
  "ios-default-text": "#a2a2a2",
};

export default vars;
